version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./DishMasters_Frontend/dist:/var/www/html/public/react
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./storage:/home/DishMasters/DishMasters/storage
    depends_on:
      - laravel

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./DishMasters_Frontend/dist:/var/www/html/public/react
      - ./nginx/laravel.conf:/etc/nginx/conf.d/laravel.conf
      - ./storage:/home/DishMasters/DishMasters/storage
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=dishmasterDB
      - DB_USERNAME=ubuntu
      - DB_PASSWORD=ubuntu
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ubuntu
      - MYSQL_DATABASE=dishmasterDB
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
